### ISSUE TITLE
Request module

### ISSUE THREAD

**Issue by monica1131** [vm6502q/ProjectQ#14]
When I try to call the backend in projectQ, it gives me an error "no module named request". How to get rid of this error?

**Comment by bennbollay** [comment]
You need to install the dependencies in the requirements.txt file:
```
pip install -r requirements.txt
```

Take a look at the ProjectQ home page and installation instructions for more details!

**Comment by WrathfulSpatula** [comment]
Thanks for opening the issue, @monica1131. The Qrack backend is "hacked in" _to_ _replace_ _the_ _default_ _simulator_ rather than as a "backend" as ProjectQ intends. (The reason for this is that we wanted downstream dependencies to immediately run on Qrack without any code modification whatsoever.) When you install this fork of ProjectQ, you use the global option "--with-qracksimulator" so that Qrack replaces the default simulator.

Benn seems to have some idea what issue you ran into, but we're here to help. If you want the Qrack simulator, use this fork. If you're looking for general ProjectQ support, that's back in the parent fork.
