### ISSUE TITLE
pybind11 dependancy in pip3 install ProjectQ

### ISSUE THREAD

**Issue by twobombs** [vm6502q/ProjectQ#8]
I'm working on a Dockerized Qrack-ProjectQ-SimulaQron container and found that the requirements for the pip3 install projectq missed the pybind11 dependancy:

![Screenshot 2019-04-15 at 14 44 15](https://user-images.githubusercontent.com/12692227/56136315-d54d7d00-5f92-11e9-86b0-51750e47ad6f.png)

installing pybind11 before installing ProjectQ fixes this:

![Screenshot 2019-04-15 at 15 24 10](https://user-images.githubusercontent.com/12692227/56136371-f31ae200-5f92-11e9-977a-85248b65361c.png)

So methinks adding pybind11 as a requirement for the correct installation of ProjectQ is in place IMHO.

**Comment by WrathfulSpatula** [comment]
@twobombs You're right, I've noticed this before, now that you mention it. It's been an issue for me, as well.

However, the vm6502q fork of ProjectQ seeks to provide the minimum possible diff, relative the original ProjectQ repo, in order to just provide Qrack simulator support. This is an issue common to the original ProjectQ repo, which also uses pybind11 for its default C++ simulator.

If you haven't, please open this issue on the original ProjectQ repo. I believe they have the same issue, for compiling their default C++ simulator with pybind11. They'd probably like to address it directly, and then I can pull the update into this fork.

We can keep this issue open, until this is resolved by one means or another.

**Comment by twobombs** [comment]
Ah, missed the fact that this is a fork of another project. 
Have posted (the same) inquiry in their neck of the woods.
This issue can be closed and/or paused.

thanks
